output_dir: "./gpt2-model"
num_train_epochs: 3
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
logging_dir: "./logs"
logging_steps: 500
save_total_limit: 3
save_steps: 1000
deepspeed_config: "ds_config.json"
